const sidebars = {
  tutorialSidebar: [
    'index',
    {
      type: 'category',
      label: 'Activation',
      items: [
        'activation/github-pages-cloudflare',
      ],
    },
    {
      type: 'category',
      label: 'Governance',
      items: [
        'governance/current-visible-updates',
        'ADMISSIBILITY_WIKI_MIRROR_HANDOFF',
        'governance/public-share-readiness',
        'governance/intake-api-final-activation-handoff',
        'governance/proposal-governance-classes',
        'governance/editorial-policy',
        'governance/page-template',
        'governance/terminology-convergence',
        'governance/transition-origin-governance',
        'governance/manifest-receipt-submission',
        'governance/proposal-intake-interface',
        'governance/proposal-intake-backend-contract',
        'governance/proposal-intake-api-deployment',
        'governance/proposal-lifecycle',
        'governance/decision-record',
        'governance/relationship-status-summary',
        'governance/site-bridge-status',
        'governance/admissibility-wiki-ai-entity',
        'governance/validation',
        'governance/current-task-sync',
        'governance/repo-standards-integration',
        'governance/repo-standards-installation-bundle',
        'governance/repo-standards-validation-runbook',
        'governance/repo-preflight',
        'governance/governed-ecosystem-index',
        'governance/governed-ecosystem-transitions',
        'governance/governed-llm-reconstructive-search',
        'governance/governed-llm-activation-map',
        'governance/governed-llm-demo-overview',
        'governance/governed-llm-demo-verification',
        'governance/governed-llm-site-verification',
        'governance/governed-llm-deployment-status',
        'governance/governed-llm-archive-handoff',
        'governance/external-frameworks-as-input-class',
        'governance/governed-input-classes',
        'governance/governed-output-classes',
        'governance/governed-transition-map',
        'governance/capability-lifecycle',
        'governance/ecosystem-capability-status',
      ],
    },
    {
      type: 'category',
      label: 'Glossary',
      items: [
        'glossary/index',
        'glossary/admissibility',
        'glossary/transition',
        'glossary/authority-class',
        'glossary/policy-reference',
        'glossary/evidence-posture',
        'glossary/review-posture',
        'glossary/drift',
        'glossary/commit-time-authority',
        'glossary/commit-time-validity',
        'glossary/receipt-bound-execution',
        'glossary/governance-boundary',
        'glossary/reconstructability',
      ],
    },
    {
      type: 'category',
      label: 'Formalisms',
      items: [
        'formalisms/index',
        'formalisms/original-drawing-reference',
        'formalisms/disciplinary-translation-groundwork',
        'formalisms/translation-records',
        'formalisms/mathematics-crosswalk',
        'formalisms/external-physics-translation-records',
        'formalisms/external-bibliographic-intake',
        'formalisms/canonical-catalog',
        'formalisms/runtime-transition-governance',
        'formalisms/coherency-horizon',
        'formalisms/commit-time-admissibility',
        'formalisms/irreversibility-inference-convergence-theorem',
      ],
    },
    {
      type: 'category',
      label: 'External Frameworks',
      items: [
        'external-frameworks/index',
        'external-frameworks/governance-observatory-protocol',
        'external-frameworks/commit-time-interoperability-contract',
        'external-frameworks/glm',
        'external-frameworks/evide',
        'external-frameworks/asro',
        'external-frameworks/decisionassure',
        'external-frameworks/mindforge',
        'external-frameworks/care-runtime',
      ],
    },
    {
      type: 'category',
      label: 'Research',
      items: [
        'research/terminology-overlap-research-notes',
      ],
    },
    {
      type: 'category',
      label: 'StegVerse',
      items: [
        'stegverse/stegcore',
        'stegverse/stegcge',
        'stegverse/tv-tvc',
        'stegverse/transition-table',
        'stegverse/transition-element-code-representation',
      ],
    },
    {
      type: 'category',
      label: 'Comparisons',
      items: [
        'comparisons/admissibility-vs-continuity',
        'comparisons/approval-vs-execution',
        'comparisons/visibility-vs-governance',
        'comparisons/auditability-vs-admissibility',
      ],
    },
    {
      type: 'category',
      label: 'Proof Path',
      items: [
        'proof-path/minimal-public-proof-path',
        'proof-path/transition-cell-example',
        'proof-path/receipt-example',
        'proof-path/replay-example',
        'proof-path/deny-example',
        'proof-path/escalate-example',
        'proof-path/refuse-example',
        'proof-path/drift-denial-example',
      ],
    },
    {
      type: 'category',
      label: 'Ontology',
      items: [
        'ontology/machine-readable-vocabulary',
      ],
    },
    {
      type: 'category',
      label: 'Essays',
      items: [
        'essays/why-admissibility-matters',
        'essays/consequence-standing',
      ],
    },
  ],
};

export default sidebars;
